export const ROUTES = {
  login: "/login",
  dashboard: "/dashboard",
  vendors: "/vendors",
  vendorNew: "/vendors/new",
  vendorDetail: (id: string) => `/vendors/${id}`,
  invoiceDetail: (id: string) => `/invoices/${id}`,
  invoiceReceive: (id: string) => `/invoices/${id}/receive`,
  products: "/products",
  productsCompareAll: "/products/compare",
  categories: "/categories",
  activityLogs: "/activity-logs",
  users: "/users",
  settings: "/settings",
  profile: "/profile",
} as const;
